export const COLLAPSE_MENU = "COLLAPSE_MENU";
export const COLLAPSE_TOGGLE = "COLLAPSE_TOGGLE";
export const FULL_SCREEN = "FULL_SCREEN";
export const FULL_SCREEN_EXIT = "FULL_SCREEN_EXIT";
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";
export const NAV_CONTENT_LEAVE = "NAV_CONTENT_LEAVE";
export const NAV_COLLAPSE_LEAVE = "NAV_COLLAPSE_LEAVE";
export const SUBMITTING_REQUEST_STATUS = "SUBMITTING_REQUEST_STATUS";
export const LOADED_USER_AUTH_SUCCESS = "LOADED_USER_AUTH_SUCCESS";
export const LOADED_USER_PARAM_SUCCESS = "LOADED_USER_PARAM_SUCCESS";
export const LOADED_USER_INFO_SUCCESS = "LOADED_USER_INFO_SUCCESS";
export const LOADED_USER_FORGOT_SUCCESS = "LOADED_USER_FORGOT_SUCCESS";
export const LOADED_SETTING_INFO_SUCCESS = "LOADED_SETTING_INFO_SUCCESS";
export const LOADED_DATA_SUCCESS = "LOADED_DATA_SUCCESS";
export const LOADED_EMAIL_DATA_SUCCESS = "LOADED_EMAIL_DATA_SUCCESS";
export const LOADED_PAGE_DATA_SUCCESS = "LOADED_PAGE_DATA_SUCCESS";
export const LOAD_PAGINATION_DATA_SUCCESS = "LOAD_PAGINATION_DATA_SUCCESS";
export const NETWORK_REQUEST_STATUS = "NETWORK_REQUEST_STATUS";
export const TABLE_HEAD_REQUEST_STATUS = "TABLE_HEAD_REQUEST_STATUS";
export const LOAD_REQUEST_STATUS = "LOAD_REQUEST_STATUS";
export const LOADED_FAQ_DATA_SUCCESS = "LOADED_FAQ_DATA_SUCCESS";
export const LOADED_EMAIL_PARAM_SUCCESS = "LOADED_EMAIL_PARAM_SUCCESS";
export const LOAD_STATUS = "LOAD_STATUS";
export const LOAD_PATH_NAME = "LOAD_PATH_NAME";
export const LOADED_CUSTOMER_DATA_SUCCESS = "LOADED_CUSTOMER_DATA_SUCCESS";
export const LOADED_DASHBOARD_INFO_SUCCESS = "LOADED_DASHBOARD_INFO_SUCCESS";
export const LOADED_USER_NOTIFICATION_DATA_SUCCESS =
  "LOADED_USER_NOTIFICATION_DATA_SUCCESS";
export const LOADED_USER_LIST_DATA_SUCCESS = "LOADED_USER_LIST_DATA_SUCCESS";
export const LOADED_CONTACT_DATA_SUCCESS = "LOADED_CONTACT_DATA_SUCCESS";
export const LOADED_TOASTER_INFO_SUCCESS = "LOADED_TOASTER_INFO_SUCCESS";
export const LOADED_DIALOG_OPEN_SUCCESS = "LOADED_DIALOG_OPEN_SUCCESS";
export const LOADED_NOTIFICATION_COUNT_SUCCESS =
  "LOADED_NOTIFICATION_COUNT_SUCCESS";
export const LOADED_REQUEST_DATA_SUCCESS = "LOADED_REQUEST_DATA_SUCCESS";
export const SUBMITTING_PRE_LOADER = "SUBMITTING_PRE_LOADER";
export const LOADED_SUB_ADMIN_DATA_SUCCESS = "LOADED_SUB_ADMIN_DATA_SUCCESS";
export const LOADED_LANGUAGE_LIST_DATA_SUCCESS =
  "LOADED_LANGUAGE_LIST_DATA_SUCCESS";
export const LOADED_PERMISSION_DATA_SUCCESS = "LOADED_PERMISSION_DATA_SUCCESS";
export const LOADED_SELECT_CATEGORY_DATA_SUCCESS =
  "LOADED_SELECT_CATEGORY_DATA_SUCCESS";
export const LOAD_FORM_POP = "LOAD_FORM_POP";
export const LOADED_DEPARTMENT_DATA_SUCCESS = "LOADED_DEPARTMENT_DATA_SUCCESS";
export const LOADED_DEPARTMENT_LISTING_SUCCESS =
  "LOADED_DEPARTMENT_LISTING_SUCCESS";
export const LOADED_CATEGORY_DATA_SUCCESS = "LOADED_CATEGORY_DATA_SUCCESS";
export const LOADED_BRAND_DATA_SUCCESS = "LOADED_BRAND_DATA_SUCCESS";
export const LOADED_BANNER_DATA_SUCCESS = "LOADED_BANNER_DATA_SUCCESS";
export const LOADED_SUBSCRIPTION_DATA_SUCCESS =
  "LOADED_SUBSCRIPTION_DATA_SUCCESS";
export const LOADED_SUBCATEGORY_DATA_SUCCESS =
  "LOADED_SUBCATEGORY_DATA_SUCCESS";
export const LOADED_BRAND_LISTING_DATA_SUCCESS =
  "LOADED_BRAND_LISTING_DATA_SUCCESS";
export const LOADED_MODEL_DATA_SUCCESS = "LOADED_MODEL_DATA_SUCCESS";
export const LOADED_COMMISSION_DATA = "LOADED_COMMISSION_DATA";
export const LOADED_COUPON_DATA_SUCCESS = "LOADED_COUPON_DATA_SUCCESS";
export const LOADED_RTL_SUCCESS = "LOADED_RTL_SUCCESS";
export const LOADED_LANGUAGE_SUCCESS = "LOADED_LANGUAGE_SUCCESS";
export const LOADED_POST_DATA_SUCCESS = "LOADED_POST_DATA_SUCCESS";
export const LOADED_ORDER_DATA_SUCCESS = "LOADED_ORDER_DATA_SUCCESS";
export const LOAD_ORDER_COUNT_DATA = "LOAD_ORDER_COUNT_DATA";
export const LOADED_ORDER_RETURN_REQUEST_DATA_SUCCESS =
  "LOADED_ORDER_RETURN_REQUEST_DATA_SUCCESS";
export const LOADED_REPORT_DATA_SUCCESS = "LOADED_REPORT_DATA_SUCCESS";
export const LOADED_REPORTED_DATA_SUCCESS = "LOADED_REPORTED_DATA_SUCCESS";
export const LOADED_USER_SELECT_SUCCESS = "LOADED_USER_SELECT_SUCCESS";
export const LOADED_VERIFY_REQUEST_SUCCESS = "LOADED_VERIFY_REQUEST_SUCCESS";
export const LOADED_BOOST_DATA_SUCCESS = "LOADED_BOOST_DATA_SUCCESS";
export const LOADED_DEFTLY_LANGUAGE = "LOADED_DEFTLY_LANGUAGE";
export const LOADED_RESPONSE_DATA_SUCCESS = "LOADED_RESPONSE_DATA_SUCCESS";
export const LOADED_USER_CHAT_DATA_SUCCESS = "LOADED_USER_CHAT_DATA_SUCCESS";
export const LOADED_CHAT_DATA_SUCCESS = "LOADED_CHAT_DATA_SUCCESS";
export const LOADED_ROOM_CHAT_DATA_SUCCESS = "LOADED_ROOM_CHAT_DATA_SUCCESS";
export const LOADED_CONDITIONAL_DATA_SUCCESS =
  "LOADED_CONDITIONAL_DATA_SUCCESS";
export const LOADED_CASH_OUT_DATA_SUCCESS = "LOADED_CASH_OUT_DATA_SUCCESS";
