export default {
  items: [
    {
      id: "pages",
      title: "",
      type: "group",
      icon: "icon-pages",
      children: [
        {
          id: "dashboard",
          title: "Dashboard",
          type: "item",
          url: "/dashboard",
          icon: "feather icon-home",
        },
        {
          id: "order",
          title: "Orders Management",
          type: "collapse",
          icon: "fas fa-cart-arrow-down",
          children: [
            {
              id: "role",
              title: "Order List",
              type: "item",
              url: "/order/listing",
            },
            {
              id: "returnRequest",
              title: "Return Request",
              type: "item",
              url: "/order/return-return",
            },
          ],
        },
        {
          id: "post-item",
          title: "Post Item",
          type: "item",
          url: "/post-item",
          icon: "fas fa-people-carry",
        },
        {
          id: "sub-admin",
          title: "Sub Admins",
          type: "item",
          url: "/sub-admin",
          icon: "fas fa-briefcase",
        },
        {
          id: "users",
          title: "User Management",
          type: "collapse",
          icon: "far fa-user-circle",
          children: [
            {
              id: "customer",
              title: "Customers",
              type: "item",
              url: "/users/customer",
            },
          ],
        },
        {
          id: "cms",
          title: "CMS Management",
          type: "collapse",
          icon: "far fa-file-alt",
          children: [
            {
              id: "category",
              title: "Categories",
              type: "item",
              url: "/cms/category",
            },
            {
              id: "brand",
              title: "Brands",
              type: "item",
              url: "/cms/brand",
            },
            {
              id: "model",
              title: "Model",
              type: "item",
              url: "/cms/model",
            },
            {
              id: "page",
              title: "Pages",
              type: "item",
              url: "/cms/page",
            },
            {
              id: "email",
              title: "Email Templates",
              type: "item",
              url: "/cms/email",
            },
            {
              id: "faq",
              title: "FAQ's",
              type: "item",
              url: "/cms/faq",
            },
            {
              id: "banner",
              title: "Banners",
              type: "item",
              url: "/cms/banner",
            },
          ],
        },
        {
          id: "cash-out",
          title: "Cash Out Request",
          type: "item",
          url: "/cash-out-request",
          icon: "fas fa-money-bill",
        },
        {
          id: "subscription",
          title: "Subscription Plan",
          type: "item",
          url: "/subscription",
          icon: "fa fa-list",
        },
        {
          id: "doffo-verify",
          title: "Doffo Verify Request",
          type: "item",
          url: "/doffo-verify",
          icon: "fa fa-users",
        },
        {
          id: "doffo-boost-report",
          title: "Doffo Boost Report",
          type: "item",
          url: "/doffo-boost-report",
          icon: "fas fa-hand-holding-usd",
        },
        {
          id: "coupon",
          title: "Coupons & Gift Vouchers",
          type: "item",
          url: "/coupon",
          icon: "fas fa-gift",
        },
        // {
        //   id: "report-items",
        //   title: "Reported Items",
        //   type: "item",
        //   url: "/report-items",
        //   icon: "fas fa-flag",
        // },
        {
          id: "notification",
          title: "Send Notification",
          type: "item",
          url: "/send-notification",
          icon: "fa fa-bell",
        },
        // {
        //   id: "commission",
        //   title: "Commission",
        //   type: "item",
        //   url: "/commission",
        //   icon: "fa fa-percent",
        // },
        {
          id: "settings",
          title: "Platform Settings",
          type: "item",
          url: "/setting",
          icon: "fas fa-tools",
        },
        {
          id: "chat",
          title: "Chat",
          type: "item",
          url: "/chat",
          icon: "fa fa-comments",
        },
      ],
    },
  ],
};
